version: '3.9'
services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    expose:
      - '5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./ProjectSourceCode/src/init_data:/docker-entrypoint-initdb.d

  web:
    image: node:lts
    # user: 'node'
    working_dir: /ProjectSourceCode
    env_file: .env
    depends_on:
      - db
    ports:
      - '3000:3000'
    volumes:
      - ./ProjectSourceCode:/ProjectSourceCode
    command: 'npm start'

volumes:
  postgres-data: